### ISSUE TITLE
Refactor node provider DB Schema

### ISSUE THREAD

**Issue by louisevelayo** [aviate-labs/node-monitor#92]
🚧 WIP: Add changes that need to be made to the DB schema below:

- [ ] Create a NP principal <> slack channel name table
- [ ] Create a NP principal <> telegram chat id table
- [ ] Remove column `telegram_channel_id`

**Comment by mourginakis** [comment]
So this PR will mostly deal with refactoring our postgres DB schema and our `NodeProviderDB` class.

Right now the `NodeProviderDB` class contains 4 tables:
- `subscribers` (one to one)
- `email_lookup` (one to many)
- `channel_lookup` (one to many)
- `node_label_lookup` (one to one)


The problem is that this doesn't accurately reflect the nature of our data. So we will have the following:
- `subscribers` (one to one)
- `email_lookup` (one to many)
- `slack_channel_lookup` (one to many)
- `telegram_chat_lookup` (one to many)
- `node_label_lookup` (one to many)

The benefits of denoting the `one to many` or `one to one` relationship (surrogate/natural keys respectively) lies in that we can create significantly smaller functions that deal with the read/write operations. This will significantly reduce code bloat.


On top of this, we will refactor the class itself so that the desired database schema is stored directly in the class attributes. The class will not create these tables on init, instead it will validate the schema is correct in the `test_node_provider_db.py` file.

We will also move a significant amount of the logic outside of the class, and place it in the tests file instead.


Please note that this comment is incomplete, I will finish it soon.
